services:
  chatbot-oracle:
    build: .
    image: "docker.io/kristjangrm/oracle-app"
    platform: linux/amd64
    environment:
      - CONTRACT_ADDRESS=${CONTRACT_ADDRESS}
      - PRIVATE_KEY=${PRIVATE_KEY}
      - NETWORK_NAME=${NETWORK_NAME:-sapphire-testnet}
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
    volumes:
      - /run/rofl-appd.sock:/run/rofl-appd.sock